<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.red-ead.tools</groupId>
    <artifactId>benchmark-runtime</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <red-ohc.version>1.0.0-SNAPSHOT</red-ohc.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-core</artifactId>
            <version>1.37</version>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>red</id>
            <dependencies>
                <dependency>
                    <groupId>io.github.red-ead</groupId>
                    <artifactId>red-ohc-core</artifactId>
                    <version>${red-ohc.version}</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>snazy</id>
            <dependencies>
                <dependency>
                    <groupId>org.caffinitas.ohc</groupId>
                    <artifactId>ohc-core</artifactId>
                    <version>0.7.4</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>ehcache</id>
            <dependencies>
                <dependency>
                    <groupId>org.ehcache</groupId>
                    <artifactId>ehcache</artifactId>
                    <version>3.10.8</version>
                    <exclusions>
                        <exclusion>
                            <groupId>javax.cache</groupId>
                            <artifactId>cache-api</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.glassfish.jaxb</groupId>
                            <artifactId>jaxb-runtime</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>mapdb</id>
            <dependencies>
                <dependency>
                    <groupId>org.mapdb</groupId>
                    <artifactId>mapdb</artifactId>
                    <version>3.1.0</version>
                </dependency>
            </dependencies>
            <dependencyManagement>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-stdlib</artifactId>
                        <version>1.9.25</version>
                    </dependency>
                    <dependency>
                        <groupId>org.eclipse.collections</groupId>
                        <artifactId>eclipse-collections-api</artifactId>
                        <version>10.4.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.eclipse.collections</groupId>
                        <artifactId>eclipse-collections</artifactId>
                        <version>10.4.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.eclipse.collections</groupId>
                        <artifactId>eclipse-collections-forkjoin</artifactId>
                        <version>10.4.0</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>33.3.1-jre</version>
                    </dependency>
                </dependencies>
            </dependencyManagement>
        </profile>
        <profile>
            <id>chronicle</id>
            <dependencies>
                <dependency>
                    <groupId>net.openhft</groupId>
                    <artifactId>chronicle-map</artifactId>
                    <version>3.27ea1</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>redis</id>
            <dependencies>
                <dependency>
                    <groupId>redis.clients</groupId>
                    <artifactId>jedis</artifactId>
                    <version>5.0.2</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
